// src/components/layers/AILayer.tsx
import React from 'react';
import { type GameState, AI_CORE_TICK_RATE_PER_LEVEL, MAX_ENTROPY } from '../../types/gameState';

interface AILayerProps {
  gameState: GameState;
}

const AILayer: React.FC<AILayerProps> = ({ gameState }) => {
  // Base rate from AI cores
  const baseAiTickRate = AI_CORE_TICK_RATE_PER_LEVEL * gameState.upgrades.aiCoreLevel;
  // Rate after meta knowledge tick multiplier
  const metaBuffedAiTickRate = baseAiTickRate * gameState.metaKnowledge.buffs.tickMultiplier;
  // Rate after entropy factor (max 50% reduction from entropy)
  const entropyFactor = 1 - (gameState.resources.entropy / (MAX_ENTROPY * 2));
  const effectiveAiTickRate = metaBuffedAiTickRate * Math.max(0, entropyFactor);


  return (
    <div className="animate-fadeIn">
      <h3 className="text-xl font-semibold mb-4 text-accent-primary">AI Subsystem Control</h3>
      
      <div className="bg-gray-900 p-4 rounded border border-border-secondary shadow-md mb-4">
        <p className="mb-4 text-text-secondary text-sm">
          The AI Layer utilizes autonomous computational agents to generate Ticks passively.
          Upgrading AI Cores enhances their processing power and base tick output.
          AI contributions are also affected by global tick multipliers (from Meta-Knowledge) and system entropy.
        </p>
        
        <div className="space-y-2 text-text-primary">
          <div className="flex justify-between">
            <span>AI Core Level:</span>
            <span className="font-mono">{gameState.upgrades.aiCoreLevel}</span>
          </div>
          <div className="flex justify-between">
            <span title="Base rate from AI cores only">Base AI Tick Rate:</span>
            <span className="font-mono">{baseAiTickRate.toFixed(2)} Ticks/sec</span>
          </div>
          <div className="flex justify-between">
            <span title="After Meta-Knowledge tick multiplier and entropy effects">Effective AI Tick Rate:</span>
            <span className="font-mono">{effectiveAiTickRate.toFixed(2)} Ticks/sec</span>
          </div>
          <div className="flex justify-between">
            <span title="Total ticks generated by AI since last prestige">Total Ticks by AI (this Prestige):</span>
            <span className="font-mono">{Math.floor(gameState.resources.aiAutoGeneratedTicks).toLocaleString()}</span>
          </div>
        </div>
      </div>

      <div className="bg-gray-900 p-4 rounded border border-border-secondary shadow-md">
        <h4 className="font-semibold mb-2 text-text-primary">AI Status & Future Research</h4>
        <p className="text-text-secondary text-sm">
          Currently, the AI provides a steady stream of Ticks based on its core level and system efficiency.
          Future research and development may unlock advanced capabilities:
        </p>
        <ul className="list-disc list-inside text-text-secondary text-sm mt-2 space-y-1 pl-2">
          <li>Automated code optimization routines to actively reduce entropy.</li>
          <li>Heuristic algorithms for discovering temporary system-wide buffs.</li>
          <li>Advanced pattern recognition for bonus tick generation based on specific game states.</li>
          <li>AI-driven resource management suggestions or automation.</li>
        </ul>
      </div>
    </div>
  );
};

export default AILayer;