// src/components/layers/AILayer.tsx
import React from 'react';
import { type GameState, AI_CORE_TICK_RATE_PER_LEVEL } from '../../types/gameState';

interface AILayerProps {
  gameState: GameState;
}

const AILayer: React.FC<AILayerProps> = ({ gameState }) => {
  const aiTickRate = AI_CORE_TICK_RATE_PER_LEVEL * gameState.upgrades.aiCoreLevel * gameState.metaKnowledge.buffs.tickMultiplier;

  return (
    <div className="animate-fadeIn">
      <h3 className="text-xl mb-4 text-accent-primary">AI Layer</h3>
      
      <div className="bg-background-secondary p-4 rounded border border-border-primary shadow-md mb-4">
        <p className="mb-4 text-text-secondary">
          The AI Layer employs autonomous agents to generate Ticks passively.
          Upgrade AI Cores to enhance their processing power and tick output.
          AI contributions are also affected by global tick multipliers from Prestige.
        </p>
        
        <div className="space-y-2 text-text-primary">
          <div className="flex justify-between">
            <span>AI Core Level:</span>
            <span>{gameState.upgrades.aiCoreLevel}</span>
          </div>
          <div className="flex justify-between">
            <span>Passive Tick Generation (from AI):</span>
            <span>{aiTickRate.toFixed(2)} Ticks/sec</span>
          </div>
          <div className="flex justify-between">
            <span>Total Ticks Generated by AI (this session):</span>
            <span>{Math.floor(gameState.resources.aiAutoGeneratedTicks)}</span>
          </div>
        </div>
      </div>

      <div className="bg-background-secondary p-4 rounded border border-border-primary shadow-md">
        <h4 className="font-semibold mb-2 text-text-primary">AI Status & Future Enhancements</h4>
        <p className="text-text-secondary text-sm">
          Currently, AI provides a steady stream of Ticks. Future upgrades may unlock:
        </p>
        <ul className="list-disc list-inside text-text-secondary text-sm mt-2 space-y-1">
          <li>AI-driven code optimization to reduce entropy.</li>
          <li>Automated discovery of new algorithms (unlocking temporary buffs).</li>
          <li>A "Debugger Minigame" where you assist the AI for rewards.</li>
        </ul>
      </div>
    </div>
  );
};

export default AILayer;