# .github/workflows/echo-deploy.yml
# This workflow deploys the echo project to a separate repository
name: Deploy Echo

on:
  push:
    branches: [main]
    paths:
      - 'packages/echo/**'
      - '.github/workflows/echo-deploy.yml'
  workflow_dispatch:

jobs:
  call-deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      package-name: echo
      dist-folder: packages/echo/dist
      repository-name: evanlin23/echo
      external: true
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
