# .github/workflows/struct-deploy.yml
# This workflow deploys the struct project to a separate repository
name: Deploy Struct

on:
  push:
    branches: [main]
    paths:
      - 'packages/struct/**'
      - '.github/workflows/struct-deploy.yml'
  workflow_dispatch:

jobs:
  call-deploy:
    permissions:
      contents: write
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      package-name: struct
      dist-folder: packages/struct/dist
      repository-name: evanlin23/struct
      external: true
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
