# .github/workflows/typedef-deploy.yml
# This workflow deploys the typedef project to the original repository
name: Deploy Typedef

on:
  push:
    branches: [main]
    paths:
      - 'packages/typedef/**'
      - '.github/workflows/typedef-deploy.yml'
  workflow_dispatch:

jobs:
  call-deploy:
    permissions:
      contents: write
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      package-name: typedef
      dist-folder: packages/typedef/dist
      repository-name: ''
      external: false
